"""add_admin_models_administrators_payments_amazon_accounts_proxy_servers

Revision ID: 07153f02cb60
Revises: 0dd603d88f6e
Create Date: 2025-07-03 22:59:41.212529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07153f02cb60'
down_revision = '0dd603d88f6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 