"""add_crawler_model_for_admin_management

Revision ID: 15b2d55c3072
Revises: 07153f02cb60
Create Date: 2025-07-04 19:19:09.026500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b2d55c3072'
down_revision = '07153f02cb60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 