"""Add prompt templates and content generation tables

Revision ID: 7216858f0a04
Revises: 
Create Date: 2025-07-01 18:40:10.649246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7216858f0a04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('ai_provider', sa.String(length=30), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('product_data', sa.JSON(), nullable=True),
    sa.Column('reviews_analyzed', sa.Integer(), nullable=True),
    sa.Column('input_parameters', sa.JSON(), nullable=True),
    sa.Column('temperature', sa.String(length=10), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.String(length=10), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generated_content'))
    )
    op.create_index(op.f('ix_ai_generated_content_id'), 'ai_generated_content', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generated_content_template_type'), 'ai_generated_content', ['template_type'], unique=False)
    op.create_table('content_generation_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('total_generations', sa.Integer(), nullable=True),
    sa.Column('successful_generations', sa.Integer(), nullable=True),
    sa.Column('failed_generations', sa.Integer(), nullable=True),
    sa.Column('openai_usage', sa.Integer(), nullable=True),
    sa.Column('deepseek_usage', sa.Integer(), nullable=True),
    sa.Column('product_descriptions', sa.Integer(), nullable=True),
    sa.Column('faqs_generated', sa.Integer(), nullable=True),
    sa.Column('comparisons_generated', sa.Integer(), nullable=True),
    sa.Column('avg_generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('avg_quality_score', sa.String(length=10), nullable=True),
    sa.Column('avg_user_rating', sa.String(length=10), nullable=True),
    sa.Column('unique_products_analyzed', sa.Integer(), nullable=True),
    sa.Column('total_reviews_processed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_generation_stats'))
    )
    op.create_index(op.f('ix_content_generation_stats_date'), 'content_generation_stats', ['date'], unique=False)
    op.create_index(op.f('ix_content_generation_stats_id'), 'content_generation_stats', ['id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('default_temperature', sa.String(length=10), nullable=True),
    sa.Column('default_max_tokens', sa.Integer(), nullable=True),
    sa.Column('supported_providers', sa.JSON(), nullable=True),
    sa.Column('required_variables', sa.JSON(), nullable=True),
    sa.Column('optional_variables', sa.JSON(), nullable=True),
    sa.Column('example_output', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates'))
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_template_type'), 'prompt_templates', ['template_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_templates_template_type'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_content_generation_stats_id'), table_name='content_generation_stats')
    op.drop_index(op.f('ix_content_generation_stats_date'), table_name='content_generation_stats')
    op.drop_table('content_generation_stats')
    op.drop_index(op.f('ix_ai_generated_content_template_type'), table_name='ai_generated_content')
    op.drop_index(op.f('ix_ai_generated_content_id'), table_name='ai_generated_content')
    op.drop_table('ai_generated_content')
    # ### end Alembic commands ### 