"""add_content_length_to_prompt_templates

Revision ID: 9ba783db051d
Revises: 15b2d55c3072
Create Date: 2025-07-06 09:38:31.719442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba783db051d'
down_revision = '15b2d55c3072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('content_length', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_templates', 'content_length')
    # ### end Alembic commands ### 